### PR TITLE
Upgrade AWS SDK to V3

### PR DESCRIPTION
**Pull request by qarol**

### CODE REVIEW

**Comment by henrylawson** [comment]
Thanks for your contribution

**Comment by henrylawson** [comment]
I have released https://rubygems.org/gems/dynamodb-migration/versions/0.8.0 with your changes

**Comment by henrylawson** [comment]
This also resolved https://github.com/henrylawson/dynamodb-migration/issues/6

**Comment by qarol** [comment]
Perfect, thanks!

**Pull request merged**
